### ISSUE TITLE
ERR_REQUIRE_ESM when upgrading from run-jxa 2 to 3

### ISSUE THREAD

**Issue by tommyfr** [sindresorhus/run-jxa#6]
When upgrading from run-jxa 2 to 3, I get this error (Electron 18.2.3, Typescript 4.8.3):

[ERR_REQUIRE_ESM]: require() of ES Module .../node_modules/run-jxa/index.js from [filename] not supported.
Instead change the require of index.js in [filename] to a dynamic import() which is available in all CommonJS modules

Has anyone solved this already ?

Thanks !

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
